'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("fractal_explorer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  100000 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property barnsley_fern_max_iterations() As String
            Get
                Return ResourceManager.GetString("barnsley_fern.max_iterations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  barnsley_fern.png に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property barnsley_fern_output_file() As String
            Get
                Return ResourceManager.GetString("barnsley_fern.output_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  10.0 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property barnsley_fern_size_x() As String
            Get
                Return ResourceManager.GetString("barnsley_fern.size_x", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  95.0 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property barnsley_fern_size_y() As String
            Get
                Return ResourceManager.GetString("barnsley_fern.size_y", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  48.0 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property barnsley_fern_start_x() As String
            Get
                Return ResourceManager.GetString("barnsley_fern.start_x", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  0.0 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property barnsley_fern_start_y() As String
            Get
                Return ResourceManager.GetString("barnsley_fern.start_y", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  90 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property barnsley_fern_zoom() As String
            Get
                Return ResourceManager.GetString("barnsley_fern.zoom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  20 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property burning_ship_max_iterations() As String
            Get
                Return ResourceManager.GetString("burning_ship.max_iterations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  burning_ship.png に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property burning_ship_output_file() As String
            Get
                Return ResourceManager.GetString("burning_ship.output_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  10 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property burning_ship_threshold() As String
            Get
                Return ResourceManager.GetString("burning_ship.threshold", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  -1.7 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property burning_ship_x_max() As String
            Get
                Return ResourceManager.GetString("burning_ship.x_max", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  -1.8 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property burning_ship_x_min() As String
            Get
                Return ResourceManager.GetString("burning_ship.x_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  0.02 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property burning_ship_y_max() As String
            Get
                Return ResourceManager.GetString("burning_ship.y_max", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  -0.1 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property burning_ship_y_min() As String
            Get
                Return ResourceManager.GetString("burning_ship.y_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  210 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property dragon_curve_delta() As String
            Get
                Return ResourceManager.GetString("dragon_curve.delta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  15 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property dragon_curve_max_iterations() As String
            Get
                Return ResourceManager.GetString("dragon_curve.max_iterations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  dragon_curve.png に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property dragon_curve_output_file() As String
            Get
                Return ResourceManager.GetString("dragon_curve.output_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  33 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property dragon_curve_x() As String
            Get
                Return ResourceManager.GetString("dragon_curve.x", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  75 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property dragon_curve_y() As String
            Get
                Return ResourceManager.GetString("dragon_curve.y", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  items.txt に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property global_artifact_filename() As String
            Get
                Return ResourceManager.GetString("global.artifact_filename", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  512 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property global_height() As String
            Get
                Return ResourceManager.GetString("global.height", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ./dist に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property global_output_directory() As String
            Get
                Return ResourceManager.GetString("global.output_directory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  512 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property global_width() As String
            Get
                Return ResourceManager.GetString("global.width", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  0.6 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property julia_c_im() As String
            Get
                Return ResourceManager.GetString("julia.c_im", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  -0.4 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property julia_c_re() As String
            Get
                Return ResourceManager.GetString("julia.c_re", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  70 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property julia_max_iterations() As String
            Get
                Return ResourceManager.GetString("julia.max_iterations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  julia.png に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property julia_output_file() As String
            Get
                Return ResourceManager.GetString("julia.output_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  4 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property julia_threshold() As String
            Get
                Return ResourceManager.GetString("julia.threshold", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  1.5 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property julia_x_max() As String
            Get
                Return ResourceManager.GetString("julia.x_max", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  -1.5 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property julia_x_min() As String
            Get
                Return ResourceManager.GetString("julia.x_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  1.5 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property julia_y_max() As String
            Get
                Return ResourceManager.GetString("julia.y_max", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  -1.5 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property julia_y_min() As String
            Get
                Return ResourceManager.GetString("julia.y_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  20 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property mandelbrot_max_iterations() As String
            Get
                Return ResourceManager.GetString("mandelbrot.max_iterations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  mandelbrot.png に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property mandelbrot_output_file() As String
            Get
                Return ResourceManager.GetString("mandelbrot.output_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  4 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property mandelbrot_threshold() As String
            Get
                Return ResourceManager.GetString("mandelbrot.threshold", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  0.8 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property mandelbrot_x_max() As String
            Get
                Return ResourceManager.GetString("mandelbrot.x_max", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  -2.2 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property mandelbrot_x_min() As String
            Get
                Return ResourceManager.GetString("mandelbrot.x_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  1.5 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property mandelbrot_y_max() As String
            Get
                Return ResourceManager.GetString("mandelbrot.y_max", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  -1.5 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property mandelbrot_y_min() As String
            Get
                Return ResourceManager.GetString("mandelbrot.y_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  20 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property pythagoras_tree_bottom() As String
            Get
                Return ResourceManager.GetString("pythagoras_tree.bottom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  60 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property pythagoras_tree_degree() As String
            Get
                Return ResourceManager.GetString("pythagoras_tree.degree", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  20 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property pythagoras_tree_left() As String
            Get
                Return ResourceManager.GetString("pythagoras_tree.left", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  10 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property pythagoras_tree_max_iterations() As String
            Get
                Return ResourceManager.GetString("pythagoras_tree.max_iterations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  pythagoras_tree.png に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property pythagoras_tree_output_file() As String
            Get
                Return ResourceManager.GetString("pythagoras_tree.output_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  15 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property pythagoras_tree_size() As String
            Get
                Return ResourceManager.GetString("pythagoras_tree.size", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  30 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property recursive_tree_degree() As String
            Get
                Return ResourceManager.GetString("recursive_tree.degree", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  25 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property recursive_tree_length() As String
            Get
                Return ResourceManager.GetString("recursive_tree.length", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  10 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property recursive_tree_max_iterations() As String
            Get
                Return ResourceManager.GetString("recursive_tree.max_iterations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  recursive_tree.png に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property recursive_tree_output_file() As String
            Get
                Return ResourceManager.GetString("recursive_tree.output_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  60 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property recursive_tree_shrink() As String
            Get
                Return ResourceManager.GetString("recursive_tree.shrink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  90 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property sierpinski_carpet_carpet_size() As String
            Get
                Return ResourceManager.GetString("sierpinski_carpet.carpet_size", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  5 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property sierpinski_carpet_max_iterations() As String
            Get
                Return ResourceManager.GetString("sierpinski_carpet.max_iterations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  sierpinski_carpet.png に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property sierpinski_carpet_output_file() As String
            Get
                Return ResourceManager.GetString("sierpinski_carpet.output_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  4 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property sierpinski_triangle_max_iterations() As String
            Get
                Return ResourceManager.GetString("sierpinski_triangle.max_iterations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  sierpinski_triangle.png に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property sierpinski_triangle_output_file() As String
            Get
                Return ResourceManager.GetString("sierpinski_triangle.output_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  80 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property sierpinski_triangle_triangle_size() As String
            Get
                Return ResourceManager.GetString("sierpinski_triangle.triangle_size", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  50 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property tricorn_max_iterations() As String
            Get
                Return ResourceManager.GetString("tricorn.max_iterations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  tricorn.png に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property tricorn_output_file() As String
            Get
                Return ResourceManager.GetString("tricorn.output_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  4 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property tricorn_threshold() As String
            Get
                Return ResourceManager.GetString("tricorn.threshold", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  1.7 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property tricorn_x_max() As String
            Get
                Return ResourceManager.GetString("tricorn.x_max", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  -2.3 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property tricorn_x_min() As String
            Get
                Return ResourceManager.GetString("tricorn.x_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  2.0 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property tricorn_y_max() As String
            Get
                Return ResourceManager.GetString("tricorn.y_max", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  -2.0 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property tricorn_y_min() As String
            Get
                Return ResourceManager.GetString("tricorn.y_min", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
