'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("fractal_explorer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  512 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property global_height() As String
            Get
                Return ResourceManager.GetString("global.height", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ./dist に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property global_output_directory() As String
            Get
                Return ResourceManager.GetString("global.output_directory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  512 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property global_width() As String
            Get
                Return ResourceManager.GetString("global.width", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  0.6 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property julia_c_im() As String
            Get
                Return ResourceManager.GetString("julia.c_im", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  -0.4 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property julia_c_re() As String
            Get
                Return ResourceManager.GetString("julia.c_re", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  70 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property julia_max_iterations() As String
            Get
                Return ResourceManager.GetString("julia.max_iterations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  julia.png に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property julia_output_file() As String
            Get
                Return ResourceManager.GetString("julia.output_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  4 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property julia_threshold() As String
            Get
                Return ResourceManager.GetString("julia.threshold", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  1.5 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property julia_x_max() As String
            Get
                Return ResourceManager.GetString("julia.x_max", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  -1.5 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property julia_x_min() As String
            Get
                Return ResourceManager.GetString("julia.x_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  1.5 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property julia_y_max() As String
            Get
                Return ResourceManager.GetString("julia.y_max", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  -1.5 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property julia_y_min() As String
            Get
                Return ResourceManager.GetString("julia.y_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  20 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property mandelbrot_max_iterations() As String
            Get
                Return ResourceManager.GetString("mandelbrot.max_iterations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  mandelbrot.png に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property mandelbrot_output_file() As String
            Get
                Return ResourceManager.GetString("mandelbrot.output_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  4 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property mandelbrot_threshold() As String
            Get
                Return ResourceManager.GetString("mandelbrot.threshold", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  0.8 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property mandelbrot_x_max() As String
            Get
                Return ResourceManager.GetString("mandelbrot.x_max", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  -2.2 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property mandelbrot_x_min() As String
            Get
                Return ResourceManager.GetString("mandelbrot.x_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  1.5 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property mandelbrot_y_max() As String
            Get
                Return ResourceManager.GetString("mandelbrot.y_max", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  -1.5 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property mandelbrot_y_min() As String
            Get
                Return ResourceManager.GetString("mandelbrot.y_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  50 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property tricorn_max_iterations() As String
            Get
                Return ResourceManager.GetString("tricorn.max_iterations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  tricorn.png に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property tricorn_output_file() As String
            Get
                Return ResourceManager.GetString("tricorn.output_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  4 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property tricorn_threshold() As String
            Get
                Return ResourceManager.GetString("tricorn.threshold", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  1.7 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property tricorn_x_max() As String
            Get
                Return ResourceManager.GetString("tricorn.x_max", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  -2.3 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property tricorn_x_min() As String
            Get
                Return ResourceManager.GetString("tricorn.x_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  2.0 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property tricorn_y_max() As String
            Get
                Return ResourceManager.GetString("tricorn.y_max", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  -2.0 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property tricorn_y_min() As String
            Get
                Return ResourceManager.GetString("tricorn.y_min", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
