name: Build

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
    - name: Build app for release
      run: msbuild ./src/Program.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
    - name: Run app
      run: ./src/bin/Release/fractal-explorer.exe
